abstract: list construct library
author: cho45 <cho45@lowreal.net>
build_requires: 
  Test::Class: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.640
license: perl
name: List-Enumerator
no_index: 
  directory: 
    - inc
    - t
requires: 
  Exception::Class: 0
  List::MoreUtils: 0
  List::Util: 0
  Moose: 0
version: 0.02
