---
abstract: 'list construct library'
author:
  - 'cho45 <cho45@lowreal.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-Enumerator
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
  Class::ISA: 0
  Devel::Symdump: 0
  Exception::Class: 0
  Filter::Util::Call: 0
  List::MoreUtils: 0
  List::Util: 0
  Sub::Exporter: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
